### ISSUE TITLE
error CS0246: The type or namespace name 'UnsafeHashMap<,>' could not be found

### ISSUE THREAD

**Issue by Filopuk** [ChiliMilk/URP_Toon#3]
Hi!
I love the shader but I am having an issue while compiling all the scripts. There is an error in ModelOutlineImporter.cs at multiple positions: 

Assets\URPToon\ChiliMilkToonShader\Tool\JTRP\Editor\Import\ModelOutlineImporter.cs(18,32): error CS0246: The type or namespace name 'UnsafeHashMap<,>' could not be found (are you missing a using directive or an assembly reference?)

Did I do something wrong or is there some issue in the code that needs to be fixed?

**Comment by ChiliMilk** [comment]
Hi, check and install "com.unity.collections" package in project.

**Comment by Filopuk** [comment]
That was the issue, it's working now! Thank you! :)
