### ISSUE TITLE
No outlines, even in sample scenes 

### ISSUE THREAD

**Issue by Filopuk** [ChiliMilk/URP_Toon#4]
Hi, I am once again asking for your technical support. I noticed I get no outlines (I checked the readme file). Outlines are not present is sample scenes too. Is there a way to fix it? I don't understand the point of the link in the readme, as it directs to a completely different project.

**Comment by ChiliMilk** [comment]
Maybe you should check Quality Settings or Outline Render Feature.

**Comment by Filopuk** [comment]
It's solved, I didn't realize I should use the URP asset from your project to make it work. It's sweet and beautiful now, thank you (๑˃̵　ᴗ　˂̵)و
